export const NATURES = [
  { name: 'Hardy', effect: 'Neutral' },
  { name: 'Lonely', effect: '+Attack, -Defense' },
  { name: 'Brave', effect: '+Attack, -Speed' },
  { name: 'Adamant', effect: '+Attack, -SpAttack' },
  { name: 'Naughty', effect: '+Attack, -SpDefense' },
  { name: 'Bold', effect: '+Defense, -Attack' },
  { name: 'Docile', effect: 'Neutral' },
  { name: 'Relaxed', effect: '+Defense, -Speed' },
  { name: 'Impish', effect: '+Defense, -SpAttack' },
  { name: 'Lax', effect: '+Defense, -SpDefense' },
  { name: 'Timid', effect: '+Speed, -Attack' },
  { name: 'Hasty', effect: '+Speed, -Defense' },
  { name: 'Serious', effect: 'Neutral' },
  { name: 'Jolly', effect: '+Speed, -SpAttack' },
  { name: 'Naive', effect: '+Speed, -SpDefense' },
  { name: 'Modest', effect: '+SpAttack, -Attack' },
  { name: 'Mild', effect: '+SpAttack, -Defense' },
  { name: 'Quiet', effect: '+SpAttack, -Speed' },
  { name: 'Bashful', effect: 'Neutral' },
  { name: 'Rash', effect: '+SpAttack, -SpDefense' },
  { name: 'Calm', effect: '+SpDefense, -Attack' },
  { name: 'Gentle', effect: '+SpDefense, -Defense' },
  { name: 'Sassy', effect: '+SpDefense, -Speed' },
  { name: 'Careful', effect: '+SpDefense, -SpAttack' },
  { name: 'Quirky', effect: 'Neutral' }
];

export const STARTERS = [
  { name: 'Bulbasaur', id: 1, region: 'Kanto' },
  { name: 'Charmander', id: 4, region: 'Kanto' },
  { name: 'Squirtle', id: 7, region: 'Kanto' },
  { name: 'Chikorita', id: 152, region: 'Johto' },
  { name: 'Cyndaquil', id: 155, region: 'Johto' },
  { name: 'Totodile', id: 158, region: 'Johto' },
  { name: 'Treecko', id: 252, region: 'Hoenn' },
  { name: 'Torchic', id: 255, region: 'Hoenn' },
  { name: 'Mudkip', id: 258, region: 'Hoenn' },
  { name: 'Turtwig', id: 387, region: 'Sinnoh' },
  { name: 'Chimchar', id: 390, region: 'Sinnoh' },
  { name: 'Piplup', id: 393, region: 'Sinnoh' },
  { name: 'Snivy', id: 495, region: 'Unova' },
  { name: 'Tepig', id: 498, region: 'Unova' },
  { name: 'Oshawott', id: 501, region: 'Unova' },
  { name: 'Chespin', id: 650, region: 'Kalos' },
  { name: 'Fennekin', id: 653, region: 'Kalos' },
  { name: 'Froakie', id: 656, region: 'Kalos' },
  { name: 'Rowlet', id: 722, region: 'Alola' },
  { name: 'Litten', id: 725, region: 'Alola' },
  { name: 'Popplio', id: 728, region: 'Alola' },
  { name: 'Grookey', id: 810, region: 'Galar' },
  { name: 'Scorbunny', id: 813, region: 'Galar' },
  { name: 'Sobble', id: 816, region: 'Galar' }
];